FROM python:3.11-slim

WORKDIR /usr/app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install -U pip &&\
    pip install -r requirements.txt

COPY prompt/ prompt/
COPY src/api/ src/api/

WORKDIR /usr/app/src/api
