FROM python:3.11-slim

WORKDIR /usr/app

COPY requirements.txt .

RUN pip install -U pip &&\
    pip install -r requirements.txt

COPY env/ env/
COPY prompt/ prompt/
COPY src/vector_db/ src/vector_db/
