services:
  vector-db:
    build:
      context: .
      dockerfile: Dockerfile.vector_db
    container_name: vector-db
    env_file:
      - .env
    command: python src/vector_db/main.py
    volumes:
      - ./data:/usr/app/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    depends_on:
      - vector-db
    env_file:
      - .env
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./data:/usr/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 180

  interface:
    build:
      context: .
      dockerfile: Dockerfile.interface
    container_name: interface
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 9000:9000
    command: streamlit run src/interface/main.py --server.port 9000
